#include <assert.h>

#include "boot_memory_map.h"

int main(void) {
    assert(PRIMARY_SLOT_BASE == BOOT_FLASH_BASE + BOOT_FLASH_SIZE);
    assert(SECONDARY_SLOT_BASE == PRIMARY_SLOT_BASE + PRIMARY_SLOT_SIZE);
    assert(SCRATCH_BASE == SECONDARY_SLOT_BASE + SECONDARY_SLOT_SIZE);
    assert(RESERVED_BASE == SCRATCH_BASE + SCRATCH_SIZE);
    assert(RESERVED_BASE + RESERVED_SIZE == FLASH_TOTAL_SIZE);
    assert(RESERVED_SIZE >= 2U * FLASH_SECTOR_SIZE);
    assert(APP_LINK_ORIGIN == PRIMARY_SLOT_BASE + MCUBOOT_HEADER_SIZE);
    assert(APP_LINK_SIZE == PRIMARY_SLOT_SIZE - MCUBOOT_HEADER_SIZE - MCUBOOT_TLV_RESERVE - MCUBOOT_TRAILER_RESERVE);
    return 0;
}
