add_library(hc32_libraries_headers INTERFACE)
target_include_directories(hc32_libraries_headers INTERFACE
    ${CMAKE_CURRENT_SOURCE_DIR}
)

add_library(hc32_adafruit_busio OBJECT
    Adafruit_BusIO/Adafruit_SPIDevice.cpp
)
target_include_directories(hc32_adafruit_busio PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Adafruit_BusIO
)
target_link_libraries(hc32_adafruit_busio PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
)

add_library(hc32_adafruit_gfx OBJECT
    Adafruit-GFX-Library/glcdfont.c
    Adafruit-GFX-Library/Adafruit_GFX.cpp
    Adafruit-GFX-Library/Adafruit_SPITFT.cpp
)
target_include_directories(hc32_adafruit_gfx PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Adafruit-GFX-Library
)
target_link_libraries(hc32_adafruit_gfx PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
    hc32_adafruit_busio
)

add_library(hc32_adafruit_st77xx OBJECT
    Adafruit-ST7735-Library/Adafruit_ST77xx.cpp
    Adafruit-ST7735-Library/Adafruit_ST7789.cpp
)
target_include_directories(hc32_adafruit_st77xx PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Adafruit-ST7735-Library
)
target_link_libraries(hc32_adafruit_st77xx PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
    hc32_adafruit_gfx
    hc32_adafruit_busio
)

add_library(hc32_bq40z50 OBJECT
    Bq40z50/bq40z50.cpp
)
target_include_directories(hc32_bq40z50 PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Bq40z50
)
target_link_libraries(hc32_bq40z50 PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
)

add_library(hc32_button_event OBJECT
    ButtonEvent/ButtonEvent.cpp
)
target_include_directories(hc32_button_event PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/ButtonEvent
)
target_link_libraries(hc32_button_event PUBLIC
    hc32_project_options
    hc32_arduino_headers
)

add_library(hc32_millis_task_manager OBJECT
    MillisTaskManager/MillisTaskManager.cpp
)
target_include_directories(hc32_millis_task_manager PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/MillisTaskManager
)
target_link_libraries(hc32_millis_task_manager PUBLIC
    hc32_project_options
    hc32_arduino_headers
)

add_library(hc32_mp2762a OBJECT
    Mp2762a/mp2762a.cpp
)
target_include_directories(hc32_mp2762a PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Mp2762a
)
target_link_libraries(hc32_mp2762a PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
)

file(GLOB_RECURSE PARSER_SOURCES CONFIGURE_DEPENDS
    Parser/src/*.c
    Parser/src/*.cpp
)
add_library(hc32_parser OBJECT
    ${PARSER_SOURCES}
)
target_include_directories(hc32_parser PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/Parser/include
)
target_link_libraries(hc32_parser PUBLIC
    hc32_project_options
)

add_library(hc32_easylogger OBJECT
    easylogger/src/elog.c
    easylogger/src/elog_async.c
    easylogger/src/elog_buf.c
    easylogger/src/elog_utils.c
    easylogger/port/elog_port.c
)
target_include_directories(hc32_easylogger PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/easylogger/inc
)
target_include_directories(hc32_easylogger PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/lvgl
)
target_link_libraries(hc32_easylogger PUBLIC
    hc32_project_options
    hc32_platform_headers
)

file(GLOB_RECURSE LVGL_SOURCES CONFIGURE_DEPENDS
    lvgl/src/core/*.c
    lvgl/src/draw/*.c
    lvgl/src/extra/*.c
    lvgl/src/extra/layouts/*.c
    lvgl/src/extra/themes/*.c
    lvgl/src/extra/widgets/*.c
    lvgl/src/font/*.c
    lvgl/src/hal/*.c
    lvgl/src/misc/*.c
    lvgl/src/widgets/*.c
    lvgl/porting/*.c
    lvgl/porting/*.cpp
)

foreach(pattern "/draw/arm2d/" "/draw/nxp/" "/draw/renesas/" "/draw/sdl/" "/draw/stm32_dma2d/" "/draw/swm341_dma2d/" "/extra/libs/" "/extra/others/")
    list(FILTER LVGL_SOURCES EXCLUDE REGEX "${pattern}")
endforeach()

add_library(hc32_lvgl OBJECT
    ${LVGL_SOURCES}
)
target_include_directories(hc32_lvgl PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/lvgl
    ${CMAKE_CURRENT_SOURCE_DIR}/lvgl/porting
)
target_link_libraries(hc32_lvgl PUBLIC
    hc32_project_options
    hc32_arduino_headers
    hc32_platform_headers
    hc32_adafruit_st77xx
)

add_library(hc32_libraries INTERFACE)
target_sources(hc32_libraries INTERFACE
    $<TARGET_OBJECTS:hc32_adafruit_busio>
    $<TARGET_OBJECTS:hc32_adafruit_gfx>
    $<TARGET_OBJECTS:hc32_adafruit_st77xx>
    $<TARGET_OBJECTS:hc32_bq40z50>
    $<TARGET_OBJECTS:hc32_button_event>
    $<TARGET_OBJECTS:hc32_millis_task_manager>
    $<TARGET_OBJECTS:hc32_mp2762a>
    $<TARGET_OBJECTS:hc32_parser>
    $<TARGET_OBJECTS:hc32_easylogger>
    $<TARGET_OBJECTS:hc32_lvgl>
)
target_link_libraries(hc32_libraries INTERFACE
    hc32_libraries_headers
    hc32_adafruit_busio
    hc32_adafruit_gfx
    hc32_adafruit_st77xx
    hc32_bq40z50
    hc32_button_event
    hc32_millis_task_manager
    hc32_mp2762a
    hc32_parser
    hc32_easylogger
    hc32_lvgl
)
