#ifndef USB_CONFIG_H
#define USB_CONFIG_H

#define CONFIG_USB_PRINTF(...) ((void)0)
#define CONFIG_USB_DBG_LEVEL (-1)
#define CONFIG_USB_ALIGN_SIZE 4
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 256
#define CONFIG_USBDEV_MAX_BUS 1
#define USB_NOCACHE_RAM_SECTION

#endif
