#ifndef BSP_BOARD_CONFIG_H
#define BSP_BOARD_CONFIG_H

#include <stdint.h>

#define BOOT_EXTERNAL_WATCHDOG_IDLE_LEVEL   0U
#define BOOT_EXTERNAL_WATCHDOG_ACTIVE_LEVEL 1U
#define BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS  3000U
#define BOOT_EXTERNAL_WATCHDOG_PULSE_MS     1U
#define BOOT_EXTERNAL_WATCHDOG_DEADLINE_MS  60000U
#define BOOT_STATUS_LED_ACTIVE_LEVEL        1U
#define BOOT_STATUS_LED_INACTIVE_LEVEL      0U
#define BOOT_DEBUG_PSPCR_VALUE              0x0003U

_Static_assert(BOOT_EXTERNAL_WATCHDOG_PULSE_MS > 0U, "watchdog pulse must be nonzero");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_PULSE_MS < BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS,
               "watchdog pulse must be shorter than its interval");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_INTERVAL_MS < BOOT_EXTERNAL_WATCHDOG_DEADLINE_MS,
               "watchdog feed must precede the TPL5010 deadline");
_Static_assert(BOOT_EXTERNAL_WATCHDOG_IDLE_LEVEL != BOOT_EXTERNAL_WATCHDOG_ACTIVE_LEVEL, "watchdog levels must differ");
_Static_assert(BOOT_STATUS_LED_ACTIVE_LEVEL != BOOT_STATUS_LED_INACTIVE_LEVEL, "LED levels must differ");

#if !defined(BOOT_HOST_TEST)
#define CONFIG_PERIPH_WE (LL_PERIPH_GPIO | LL_PERIPH_EFM | LL_PERIPH_FCG | LL_PERIPH_PWC_CLK_RMU | LL_PERIPH_SRAM)
#define CONFIG_PERIPH_WP (LL_PERIPH_FCG | LL_PERIPH_SRAM)
#define BSP_XTAL_PORT    GPIO_PORT_H
#define BSP_XTAL_PINS    (GPIO_PIN_00 | GPIO_PIN_01)
#define BOOT_EXTERNAL_WATCHDOG_PORT GPIO_PORT_A
#define BOOT_EXTERNAL_WATCHDOG_PIN  GPIO_PIN_06
#define BOOT_STATUS_LED_PORT        GPIO_PORT_B
#define BOOT_STATUS_LED_PIN         GPIO_PIN_05
#define BSP_LOG_UART                 CM_USART3
#define BSP_LOG_UART_CLOCK           FCG1_PERIPH_USART3
#define BSP_LOG_UART_TX_PORT         GPIO_PORT_B
#define BSP_LOG_UART_TX_PIN          GPIO_PIN_13
#define BSP_LOG_UART_TX_FUNCTION     GPIO_FUNC_32
#define BSP_LOG_UART_BAUDRATE        115200UL
#endif

#endif
